const APP = {
  PORT: 'PORT',
  NODE_ENV: 'NODE_ENV',
  APP_STAGE: 'APP_STAGE',
} as const;

const DATABASE = {
  DATABASE_URL: 'DATABASE_URL',
} as const;

const REDIS = {
  REDIS_URL: 'REDIS_URL',
};

const JWT = {
  JWT_SECRET_KEY: 'JWT_SECRET_KEY',
  JWT_ISSUER: 'JWT_ISSUER',
  JWT_ACCESS_TOKEN_EXPIRES_IN: 'JWT_ACCESS_TOKEN_EXPIRES_IN',
} as const;

const LOGGER = {
  LOGGER_LEVEL: 'LOGGER_LEVEL',
} as const;

const COOKIE = {
  ALLOW_COOKIE_DOMAIN: 'ALLOW_COOKIE_DOMAIN',
} as const;

const AWS_S3 = {
  AWS_S3_REGION: 'AWS_S3_REGION',
  AWS_S3_BUCKET_NAME: 'AWS_S3_BUCKET_NAME',
  AWS_S3_URL: 'AWS_S3_URL',
  AWS_S3_ACCESS_KEY: 'AWS_S3_ACCESS_KEY',
  AWS_S3_SECRET_KEY: 'AWS_S3_SECRET_KEY',
  AWS_S3_QUIZ_IMAGE_FILE_PATH: 'AWS_S3_QUIZ_IMAGE_FILE_PATH',
  AWS_S3_SOUND_EFFECT_FILE_PATH: 'AWS_S3_SOUND_EFFECT_FILE_PATH',
  AWS_S3_AVATAR_FILE_PATH: 'AWS_S3_AVATAR_FILE_PATH',
} as const;

const OAUTH = {
  OAUTH_ALLOW_REDIRECT_URLS: 'OAUTH_ALLOW_REDIRECT_URLS',
  OAUTH_DEFAULT_REDIRECT_URL: 'OAUTH_DEFAULT_REDIRECT_URL',
} as const;

const GOOGLE_OAUTH = {
  GOOGLE_OAUTH_CLIENT_ID: 'GOOGLE_OAUTH_CLIENT_ID',
  GOOGLE_OAUTH_CLIENT_SECRET: 'GOOGLE_OAUTH_CLIENT_SECRET',
  GOOGLE_OAUTH_CALLBACK_URL: 'GOOGLE_OAUTH_CALLBACK_URL',
  GOOGLE_OAUTH_SCOPE: 'GOOGLE_OAUTH_SCOPE',
} as const;

export const ENV_KEY = {
  ...APP,
  ...DATABASE,
  ...REDIS,
  ...JWT,
  ...LOGGER,
  ...COOKIE,
  ...AWS_S3,
  ...OAUTH,
  ...GOOGLE_OAUTH,
} as const;
